"""empty message

Revision ID: a382285194da
Revises: 
Create Date: 2023-05-28 14:48:28.567613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a382285194da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_category',
    sa.Column('expense_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expense_category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('expense_category_id')
    )
    op.create_table('income_category',
    sa.Column('income_category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('income_category_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('income_category_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expense_transaction',
    sa.Column('expense_transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expense_category_id', sa.Integer(), nullable=True),
    sa.Column('expense_transaction_amount', sa.Float(), nullable=False),
    sa.Column('expense_transaction_datetime', sa.DateTime(), nullable=True),
    sa.Column('expense_transaction_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['expense_category_id'], ['expense_category.expense_category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('expense_transaction_id')
    )
    op.create_table('income_transaction',
    sa.Column('income_transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('income_category_id', sa.Integer(), nullable=True),
    sa.Column('income_amount', sa.Float(), nullable=False),
    sa.Column('income_datetime', sa.DateTime(), nullable=True),
    sa.Column('income_description', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['income_category_id'], ['income_category.income_category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('income_transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income_transaction')
    op.drop_table('expense_transaction')
    op.drop_table('user')
    op.drop_table('income_category')
    op.drop_table('expense_category')
    # ### end Alembic commands ###
